---
name: "Test Issue"
description: "Test issue"
title: "[Test Issue] Brief description"
labels: ['test']
body:
- type: input
  attributes:
    label: Input label
    description: Input description
    placeholder: input placeholder
  validations:
    required: false
- type: dropdown
  attributes:
    label: Dropdown label
    description: Test Environment
    options:
      - dev
      - pre
      - pro
- type: textarea
  id: description
  attributes:
    label: "TextArea label"
    description: "Test description"
    placeholder: "Test placeholder"