---
name: "Test Issue"
description: "Test issue"
title: "[Test Issue] Brief description"
labels: ['test']
body:
- type: input
  attributes:
    label: Input label
    description: Input description
    placeholder: input placeholder
  validations:
    required: true

- type: dropdown
  attributes:
    label: Dropdown label
    description: Test Environment
    options:
      - dev
      - pre
      - pro
  validations:
    required: true

- type: dropdown
  attributes:
    multiple: true
    label: Dropdown multiple label
    description: Dropdown multiple description
    options:
      - option 1
      - option 2
      - option 3
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: "TextArea label"
    description: "Test description"
    placeholder: "Test placeholder"
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Checkbox label
    description: Checkbox description
    options:
      - label: Checkbox label 1
      - label: Checkbox label 2